# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

"""Regenerate the constants in tls_certificates_testing/_raw.py.

Writes ``src/charmlibs/interfaces/tls_certificates_testing/_raw.py`` in place. Three
independent artifacts:

- KEY     the default *requirer* private key (`DEFAULT_PRIVATE_KEY`). Stands in for the key a
          requirer charm holds. Never used for signing.
- CA_KEY  the private key of the testing CA. Used only to sign issued certificates.
- CERT    the testing CA's self-signed certificate, matching CA_KEY. A genuine CA:
          BasicConstraints CA:TRUE and KeyUsage keyCertSign, so a charm that performs real
          chain verification accepts it as an issuer.

KEY and CA_KEY must stay distinct: signing with the requirer's own key produces a certificate
whose chain cannot verify against CERT.

The key material is not API -- only the symbols are. Regenerating (and committing the result)
is always fine, and is never a breaking change.
"""

import datetime
import pathlib

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

_RAW_PY = (
    pathlib.Path(__file__).parent
    / "src"
    / "charmlibs"
    / "interfaces"
    / "tls_certificates_testing"
    / "_raw.py"
)
_HUNDRED_YEARS = datetime.timedelta(days=365 * 100)
_ORG = "charmlibs.interfaces.tls_certificates_testing"


def _generate_key() -> rsa.RSAPrivateKey:
    return rsa.generate_private_key(public_exponent=65537, key_size=2048)


def _pem_key(key: rsa.RSAPrivateKey) -> str:
    return key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()


def _self_signed_ca(key: rsa.RSAPrivateKey) -> x509.Certificate:
    name = x509.Name([
        x509.NameAttribute(NameOID.COUNTRY_NAME, "NZ"),
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, _ORG),
        x509.NameAttribute(NameOID.COMMON_NAME, "charmlibs testing CA"),
    ])
    now = datetime.datetime.now(datetime.timezone.utc)
    return (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)  # self-signed
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(now + _HUNDRED_YEARS)
        # These two are what make it a usable CA rather than a self-signed leaf.
        .add_extension(x509.BasicConstraints(ca=True, path_length=None), critical=True)
        .add_extension(
            x509.KeyUsage(
                digital_signature=False,
                content_commitment=False,
                key_encipherment=False,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=True,
                crl_sign=True,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        .add_extension(x509.SubjectKeyIdentifier.from_public_key(key.public_key()), critical=False)
        .sign(key, hashes.SHA256())
    )


def _constant(name: str, pem: str, comment: str) -> str:
    return f'{comment}\n{name} = """\n{pem.strip()}\n""".strip()\n'


def main() -> None:
    """Write a fresh _raw.py in place."""
    requirer_key = _generate_key()
    ca_key = _generate_key()
    ca_cert = _self_signed_ca(ca_key)

    lines = [
        "# Copyright 2026 Canonical Ltd.",
        "# See LICENSE file for licensing details.",
        "",
        "# Automatically generated by generate_raw.py -- do not edit; may be overwritten.",
        "",
        '"""Static key and certificate material for the testing library."""',
        "",
        _constant(
            "KEY",
            _pem_key(requirer_key),
            "# The default requirer private key. Never used for signing: signing with the\n"
            "# requirer's own key yields a chain that cannot verify against CERT.",
        ),
        _constant(
            "CA_KEY",
            _pem_key(ca_key),
            "# The testing CA's private key. Used only to sign issued certificates.",
        ),
        _constant(
            "CERT",
            ca_cert.public_bytes(serialization.Encoding.PEM).decode(),
            "# The testing CA's self-signed certificate, matching CA_KEY.\n"
            "# A genuine CA: BasicConstraints CA:TRUE and KeyUsage keyCertSign.",
        ),
    ]
    _RAW_PY.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
