# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

"""Regenerate the constants in certificate_transfer_testing/_raw.py.

Writes ``src/charmlibs/interfaces/certificate_transfer_testing/_raw.py`` in place.

``certificate_transfer`` moves CA certificates between charms as opaque PEM strings -- the
library never parses them. The charm under test may well parse them, though, to write a
trust store or read an expiry, so the simulated provider hands out genuine self-signed CA
certificates rather than placeholder text: ``BasicConstraints CA:TRUE`` and ``KeyUsage
keyCertSign``, valid for a hundred years so that a test never starts failing on a date.

Three of them, because the interface transfers a *set*: one is the default, and the others
let a test model a provider offering several certificates, or two providers offering
different ones. Their private keys are thrown away -- nothing on this interface signs
anything.

The certificate material is not API -- only the symbols are. Regenerating (and committing
the result) is always fine, and is never a breaking change.
"""

import datetime
import pathlib

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

_RAW_PY = (
    pathlib.Path(__file__).parent
    / 'src'
    / 'charmlibs'
    / 'interfaces'
    / 'certificate_transfer_testing'
    / '_raw.py'
)
_HUNDRED_YEARS = datetime.timedelta(days=365 * 100)
_ORG = 'charmlibs.interfaces.certificate_transfer_testing'
_COMMON_NAMES = ('charmlibs testing CA', 'charmlibs testing CA 2', 'charmlibs testing CA 3')


def _self_signed_ca(common_name: str) -> str:
    """Return the PEM of a self-signed CA certificate with a freshly generated key."""
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    name = x509.Name([
        x509.NameAttribute(NameOID.COUNTRY_NAME, 'NZ'),
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, _ORG),
        x509.NameAttribute(NameOID.COMMON_NAME, common_name),
    ])
    now = datetime.datetime.now(tz=datetime.timezone.utc)
    certificate = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now)
        .not_valid_after(now + _HUNDRED_YEARS)
        .add_extension(x509.BasicConstraints(ca=True, path_length=None), critical=True)
        .add_extension(
            x509.KeyUsage(
                digital_signature=False,
                content_commitment=False,
                key_encipherment=False,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=True,
                crl_sign=True,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        .sign(key, hashes.SHA256())
    )
    return certificate.public_bytes(serialization.Encoding.PEM).decode()


def _main() -> None:
    certificates = [_self_signed_ca(common_name) for common_name in _COMMON_NAMES]
    entries = '\n'.join(f'    """\n{pem}""".strip(),\n' for pem in certificates)
    _RAW_PY.write_text(f'''\
# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

# Automatically generated by generate_raw.py -- do not edit; may be overwritten.

"""Static certificate material for the testing library."""

# Self-signed CA certificates, valid for a hundred years. The first is what a
# ``RemoteProvider`` transfers unless the test says otherwise; the others are here so that a
# test can model several certificates, or two providers offering different ones.
CA_CERTS = (
{entries}\
)
''')


if __name__ == '__main__':
    _main()
