# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

# Automatically generated by tests/generate_keys.py -- do not edit; may be overwritten.

"""Static key material for the tests."""

# The manual test charm's private key. Deliberately NOT the key `mocked()` hands the
# library, so that tests can tell which key a certificate was issued against.
MANUAL_CHARM_KEY = """
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAyaB1Culhjx/aJVSbUQuJfTiQPXDzFGDIhbeELSu7kWu1yY23
pyiyzCmZCfssf0Wc1PsDjM10+g92wIbXpDGo5OkuVJRfsZrd7Q1rQgbQKfv4I0ql
xoUYnszd9YrXqRUo8Byzec8t45HBGS3GYnYmNsJ65u9IxUGVly2S6XouvhErMfQ4
n25RUVpFzx27SybiWEgwKE+TOtGYQKi4cn+s72UDiLH6H6k2crtAggPkADd7M5/H
xOQNSAziW3zydHam/VZ/wA/MatjVE1HobFo478wMaKrr1aopmytANe+LJ414/IDa
Uea+bk4UwIyhKFybfyPQ2hKCDBoPZo1rBK/BEQIDAQABAoIBAAumHvkASpQIrrNv
L9GHAXyn+NJp7QtZe6BZHdR3xTyVvOEeFFUeqXTY9ufwGG4qfREDhx0ajjZ30AA3
0ivg+B1wmO4HS/+Qf1+nobGk/+AbGAce9BS0AhwDoVPDP6o7yBuWRurD1OaD2GSO
Y9qysYrCofPncXx/CWfceNNPLTXrIQOEo7FjELE6eYLfG0j5n60NNo6W5op65jBi
MLh+qjO/vGGt6v71xJ20fk4sEQnQtgcZQ4E2fA8BOuFciB5w0GsWR46nHH39gLIO
MaPetzEBcw+WkukN1y+VUMhSHrCTz1KwojVysGHu+FgMp8Y4ueQe/mNGpup69NaW
KbtdgfkCgYEA45wTR3M9AJVSG+1C4S96cNPLxW61toBGjnYLiM8hYtsO/S5q+78+
eXqm3CwgqT1+AnCcy46sxVnqUFbhdwhCrDsYG5JBWgb9QMaUavXE+Nw4eYA/shG8
2zd1ySnvenMZNTv9wOv9jG/Vf0mOMYw/OQiXOV1WE9c9P+Nzybk2HBkCgYEA4sa1
bb5q3R30dKuUraGtDwFPwtOq+dFf0KZOg4oFoToo+GNmxHFASCf/+QahijHIpwu5
bRKgxPOrBnizfDxhoFpUUj/ugGDvFLbUPqx8r78FAwvfItYsY0cm0LK1t8zabm5t
UYbG1cgN5F+xjIwQzSeljEmyFN3hobYYc2Bva7kCgYEAzggt+3N5ONnx5Y20CJst
vow53JIGsxkSxUpdzo2QryeUPeKSvSe0qco42Pyo5Anh0tuVUz3nbw2haO/8T/+O
OtGTVQHjXlcNUGFxYBDxKERQasuI3OvphJaDbIElYjZmDyYq4UO91C43mG1A5eEK
Kdp46Vhv3q3rp7WAzo11SaECgYEAgIrZ9CbnNAbytd88G191VPgNWgXY+Fnx0bcy
8eSeZFEvP/w4GEmJgl0J/wH/NvIZJnbC2EyizIDCBJ0OP/GJ9Pa+rRCIBETtv/QS
QqRK2OOR17Q2+uwjpPKD0fA6iMCZX9dAJ+IZerw3A6gqX9xU+bTrZaWwR5utdZhe
K6gSACECgYBoM8f3Ogr/WA+2YcWCkksYfmCyY49AMgcHuQee9aIzxbXQPmLPzPpy
enTW6yRxQrzCXYbm1TecRrniv9E9f9j2o9NGQEo814rObPxYCX1MWfOxrDLGxZ6U
OaMyG/OnrzmYNTe0NSZbsZzzPplLzkD8K4SwQM47Fls2bcTW4qPA5A==
-----END RSA PRIVATE KEY-----
""".strip()
