# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

# Automatically generated by tests/generate_keys.py -- do not edit; may be overwritten.

"""Static key material for the tests."""

# The manual test charm's private key. Deliberately NOT the testing package's
# DEFAULT_PRIVATE_KEY, so that tests have to opt in to making the two agree.
MANUAL_CHARM_KEY = """
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAnmNT3TraD4riVUyQ3aa97IHcoX5qoX/gg2gJxjzw7QW/hVy0
13diEUF9EGmGomkw8zR0lK3WARA1tydEh8cffyH9yy2FC+GCLJA+8lzzdnp9fUx3
G+85Vd7SMLz/jNXOpYODP3RG7UNeyOfH4uNwyWk8yFd1sbAcr19nwa/l4LJvSPF7
qUQxRqO4tjDaYRX3JcimkjgbpXKxSD6ieaFOvT+R5e9v+Xt+h82cq2p4E2TaepVS
/gS7WWTvjxMW6fn3e5+/XQ+WZj5OclECeozEJ8icLXShk4nlWvL7eqhXFlXFaq9J
+7pwZ9v7wVAcTAD+yA2j6xdYIag1D01xbFghQwIDAQABAoIBAAOFijCnOtWmomKq
zvvGqyljjSAgG0cs/Ip0w+be+wJiItXYb62Xb3GacalC7LtBYypn1lcUnbysphfE
7T6m8ZnWNno6hbSea9Je1gTLMUnx7kayGQyLdKG7+xNvWFqYHxNKCcndkCgoBnxU
FFCEpcDXW1fJrgm93zK9CHsOKf/QHtj9lkMj04qFU1xAf1N08eBQ+ST4W8X+efyb
Nu1fB8TLS2BLEngIR4Dg5gp0qiEJYHfHmOYHWF5mvb0u/xzDgLMSgcPrXKWcRGkk
VeYTHd4SO7Mbb95mARalK4zlSG6ltLIhz0be0jXcwByWSlG/LNY96Mj5gTOa51DT
RgQOp80CgYEA3rZv413LMCeIat7K9fdUCFJ/ugGpRQLC0Dik/FX10wh0S8J8Vdf+
niKUk/QQRxSV+q3X5cAYMj4UzQfPZm1WHnW9NYLjhjILTAtLG/ZIAwnI3PK/7A1j
ZlYNNjGWXrwKXRX25SLD/WhFoX4VMxyGmdwzKrpimD6dLKqXnmBlWVcCgYEAtg+p
sbMjvKHALK6imz/APBSE5cgSytyAY7I/Zn9iUNdOAtYZdR3QO2alPWrk2Wk970L+
In7pzRyGBAf/vFu83B0Rcfjk9VvFuwhJU5LCfssADP9NB+PP23X+AodhFlGpbPxZ
vvEDnHxq0SQXwujEOaFDB5Kgv88dJF/r/fjxx/UCgYEA1+4AO2yz1QNvU1ahZ6sd
8VezeO+lY0CTC3jwFatuROacgtuU21IpDr8uWOi4Y4JFC6BDhAEkNIpWdpeM8Z0u
cyfqhBhcar7Yjykf8INvPGrfMcG2bLJqXk0uUA3x4fXlAm2KTIzRgz72y+XHvh95
LXH+tf2yHDQRBb58dFS3zs8CgYAyu06X+8kbiR8Z1FfvVuZkV3to5EWITcVhAox0
LU7iI/zTAYH6hqI9yy6EXMMEajUd9NcIGcFgrHATs37pp86Kr3brAWYbkMUahwaX
yS91UW/kL0fxyONkzg5H+h1tsLe7bN49PL+63ViOirYsU9xKCsu40n0EtdvzBN+n
17TX+QKBgQC7tvkrg42dVOxgOyzDd8B0k6QvvxAI1xaqwC+1FC+YZq9UTteYubxn
tAk+wr7P0/Q8v2nZg6b/FQKhiZDOSdptH3jyVeRmHk3E8N3+TD7LbARApEWJHqE/
rZNvq1MYZU2gn+3bqmJ9o1ccmCi+WzxIYk71yM3jgdEPBfykEY7dJA==
-----END RSA PRIVATE KEY-----
""".strip()
