# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

"""Tests for the static key and certificate material in ``_raw.py``.

The material is regenerated by ``generate_raw.py``, and its *values* are not API -- but its
properties are relied on by everything else here, and get them wrong and the failures appear
far away as "no certificates". These check the generator's invariants directly.
"""

from __future__ import annotations

import datetime

from cryptography import x509

from charmlibs.interfaces import tls_certificates as tls_certificates
from charmlibs.interfaces.tls_certificates_testing import _raw

CA_CERT = tls_certificates.Certificate(raw=_raw.CERT)
CA_KEY = tls_certificates.PrivateKey(raw=_raw.CA_KEY)
KEY = tls_certificates.PrivateKey(raw=_raw.KEY)


def test_the_keys_are_valid():
    """The library requires RSA, at least 2048 bits."""
    assert CA_KEY.is_valid()
    assert KEY.is_valid()


def test_the_two_keys_are_distinct():
    """Signing with a requirer's own key yields a chain that can't verify against the CA."""
    assert CA_KEY != KEY


def test_the_ca_certificate_matches_the_ca_key():
    assert CA_CERT.matches_private_key(CA_KEY)
    assert not CA_CERT.matches_private_key(KEY)


def test_the_ca_is_a_real_ca():
    """BasicConstraints CA:TRUE and KeyUsage keyCertSign, so real verification accepts it."""
    assert CA_CERT.is_ca
    cert = x509.load_pem_x509_certificate(_raw.CERT.encode())
    key_usage = cert.extensions.get_extension_for_class(x509.KeyUsage).value
    assert key_usage.key_cert_sign


def test_the_ca_is_self_signed():
    cert = x509.load_pem_x509_certificate(_raw.CERT.encode())
    assert cert.subject == cert.issuer
    cert.verify_directly_issued_by(cert)  # raises if it doesn't


def test_the_ca_has_a_subject_key_identifier():
    """The library reads it off the CA when it signs, so a CA without one can't be used."""
    cert = x509.load_pem_x509_certificate(_raw.CERT.encode())
    assert cert.extensions.get_extension_for_class(x509.SubjectKeyIdentifier)


def test_the_ca_is_valid_for_a_long_time():
    """It must outlive every certificate issued from it, in any test, for a long while."""
    now = datetime.datetime.now(datetime.timezone.utc)
    assert CA_CERT.validity_start_time <= now
    assert CA_CERT.expiry_time > now + datetime.timedelta(days=365 * 50)


def test_the_ca_signs_a_verifiable_chain():
    """End to end: a request signed by this CA verifies against it, leaf to root."""
    request = tls_certificates.CertificateRequestAttributes(common_name="example.com")
    csr = tls_certificates.CertificateSigningRequest.generate(attributes=request, private_key=KEY)
    certificate = csr.sign(ca=CA_CERT, ca_private_key=CA_KEY, validity=datetime.timedelta(days=1))
    assert csr.matches_certificate(certificate)
    assert certificate.matches_private_key(KEY)
    assert tls_certificates.chain_has_valid_order([str(certificate), str(CA_CERT)])
