# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

"""Regenerate the static key material the tests use, in tests/unit/_keys.py.

Currently just the manual test charm's private key. It stands in for a key a charm sources
itself, and must stay distinct from the key `mocked()` hands the library, so that a test can
tell the two apart (`test_the_charms_own_key_is_used` relies on this).

The key material is not API -- regenerating (and committing the result) is always fine.
"""

import pathlib

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

_KEYS_PY = pathlib.Path(__file__).parent / "unit" / "_keys.py"


def _pem_key(key: rsa.RSAPrivateKey) -> str:
    return key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()


def main() -> None:
    """Write a fresh _keys.py in place."""
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    lines = [
        "# Copyright 2026 Canonical Ltd.",
        "# See LICENSE file for licensing details.",
        "",
        "# Automatically generated by tests/generate_keys.py -- do not edit; may be overwritten.",
        "",
        '"""Static key material for the tests."""',
        "",
        "# The manual test charm's private key. Deliberately NOT the key `mocked()` hands the",
        "# library, so that tests can tell which key a certificate was issued against.",
        'MANUAL_CHARM_KEY = """',
        _pem_key(key).strip(),
        '""".strip()',
        "",
    ]
    _KEYS_PY.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
